### ISSUE TITLE
Regression: Version 2.0.7 throws UnsupportedOperationException with a single Textcomponent inside DeviceView.

### ISSUE THREAD

**Issue by watho** [appreciated/demo-helper-view#9]
Works with Version 2.0.5

Testview:
```
public class MainView extends DemoHelperView {

  public MainView() {
    withDevice(new LaptopView(new Text("test")));
  }
```

Stacktrace:
```
Caused by: java.lang.UnsupportedOperationException: This instance is immutable
	at com.vaadin.flow.dom.impl.ImmutableEmptyStyle.set(ImmutableEmptyStyle.java:39) ~[flow-server-1.2.4.jar:1.2.4]
	at com.github.appreciated.demo.helper.view.devices.Device.<init>(Device.java:17) ~[demo-helper-view-2.0.7.jar:2.0.7]
	at com.github.appreciated.demo.helper.view.devices.LaptopView.<init>(LaptopView.java:8) ~[demo-helper-view-2.0.7.jar:2.0.7]
	at de.wathoserver.vaadin.MainView.<init>(MainView.java:15) ~[classes/:na]
```

**Comment by appreciated** [comment]
Thanks for reporting!
